#!/bin/bash

if [ -f ~/.ansible-environment ]
then
	. ~/.ansible-environment
fi

if [ -f .ansible-environment ]
then
	. .ansible-environment
fi

if [ -f ~/.ansible-environment-$(basename $PWD) ]
then
	. ~/.ansible-environment-$(basename $PWD)
fi

PROJECT_NAME="$USER-$(basename $PWD)"
# sudo docker build --pull -t ghcr.io/drerik/ansible-environment:main .
sudo docker run -it --rm \
    -e PROJECT_NAME \
    --network host \
    -e ANSIBLE_INVENTORY=/workspace/inventory \
    -h ansible-runner-$PROJECT_NAME \
    -v $HOME/.ssh/id_rsa:/root/.ssh/id_rsa:ro \
    -v $HOME/.ssh/known_hosts:/root/.ssh/known_hosts:ro \
    -v $ANSIBLE_INVENTORY:/workspace/inventory:ro \
    -v $PWD:/workspace/project:ro \
    --name ansible-environment-$PROJECT_NAME \
    $ANSIBLE_ENVIRONMENT_EXTRAS ghcr.io/drerik/ansible-environment:main bash   
